# Generated by Django 4.2.5 on 2023-10-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('user_updated', models.DateTimeField(auto_now=True)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
