# Generated by Django 4.2.5 on 2023-10-31 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
