# Generated by Django 4.2.5 on 2023-11-09 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0004_message_topic_delete_useraccount_room_host_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='room',
            name='partcipants',
            field=models.ManyToManyField(related_name='partcipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
