# Generated by Django 4.2.5 on 2023-11-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
